# Generated by Django 4.0.3 on 2022-04-22 15:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='some',
            field=models.CharField(default=datetime.datetime(2022, 4, 22, 15, 28, 43, 484679, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
