# Generated by Django 4.0.3 on 2022-05-22 10:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_quiz_created_at_remove_quiz_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answer',
            field=models.CharField(default=datetime.datetime(2022, 5, 22, 10, 20, 37, 461389, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='options',
            field=models.CharField(default=datetime.datetime(2022, 5, 22, 10, 20, 45, 37390, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
