# Generated by Django 4.0.3 on 2022-05-22 10:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_quiz_answer_quiz_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question',
            field=models.CharField(default=datetime.datetime(2022, 5, 22, 10, 21, 40, 293395, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
